export const START_LOADING_ROUTE = "START_LOADING_ROUTE";
export const ERROR_LOADING_ROUTE = "ERROR_LOADING_ROUTE";

export const GET_NEW_ROUTE = "GET_NEW_ROUTE";
export const SUCCESS_NEW_ROUTE = "SUCCESS_NEW_ROUTE";
